{
	"name": "clientUtils",
	"displayName": "clientUtils",
	"version": 1,
 	"definition": "clientutils/clientUtils/clientUtils.js",
	"libraries": [],
	"model":
	{
    	"onlySelectById": {"type": "boolean", "default": true} 
 	},
 	"api":
 	{
	   	"addClass": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"className",
					"type":"string"
				}
			]
		},
		"setCss": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"propertyNameOrObject",
					"type":"string"
				},
				{
					"name":"value",
					"type":"string",
					"optional":true
				}
			]
		},
		"removeClass": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"className",
					"type":"string"
				}
			]
		},
		"toggleClass": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"className",
					"type":"string"
				},
				{
					"name":"state",
					"type":"boolean",
					"optional":true
				}
			]
		},
		"fadeIn": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"fadeOut": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"options",
					"type":"object",
					"optional":true
				}
			]
		},
		"fadeToggle": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"show": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"hide": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"toggle": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"slideDown": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		},
		"slideUp": 
	   	{
	    	"parameters":
	    	[
		    	{
					"name":"jQuerySelector",
					"type":"string"
				},
				{
					"name":"durationOrOptions",
					"type":"object",
					"optional":true
				}
			]
		}
 	}
}